Submission
LMCRC/Topos-Theory pull request #1
Opened 2024-11-04 17:58 UTC by doctorn

2024-11-19 14:39 UTC, AnthonyBordg requested changes
Dear @doctorn,

Thank you so much for your PR and the thoughtful work you’ve put into it! Your contribution is really appreciated. Your work provides a solid draft for the bijection between Grothendieck topologies and toposes. There are a few sorry placeholders to address and some adjustments needed to align with the code style guidelines. Given this, I suggest marking the PR as a draft for now. I’d love to hear your thoughts and plans for the next steps. Please let me know how I can support you in moving this forward.

2024-11-20 13:18 UTC, doctorn commented on ToposTheory/Duality.lean
> +  . sorry -- TODO(@doctorn) this is the final sentence of slide 26 in Lafforgue's presentation
I can't understand how the comment on the slide verifies this claim. I couldn't see how (a) the claim made on the slide is true or (b) why it would imply this result.

2024-11-20 13:20 UTC, doctorn commented on ToposTheory/Duality.lean
> +def idRestrictionMap {X : C} (S : Sieve X):
This saved a lot of typing and additional proof obligations. I can remove this definition but the proofs using it get needlessly fiddly as a result.

2024-11-20 13:22 UTC, doctorn commented on ToposTheory/Duality.lean
> +def restrictionMap {X : C} (S : Sieve X) {X' : C} (f : X' ⟶ X) :
Ah! I hadn't realised this... This is slightly frustrating. I added the `@[simp]` annotations because I got very tired of typing out all of the names of the definitions to unfold... I'm sure there's a better way of doing this that I haven't understood.

2024-11-20 13:25 UTC, doctorn commented on ToposTheory/Duality.lean
> +instance sheavesEquivFullSubcategory (J : GrothendieckTopology C) :
I completely agree

2024-11-20 13:25 UTC, doctorn commented on ToposTheory/Duality.lean
> +    Functor.IsRightAdjoint (fullSubcategoryInclusion (C := C ᵒᵖ ⥤ Type u) (Presheaf.IsSheaf J)) := by
Thanks!

2024-11-20 13:28 UTC, doctorn commented on ToposTheory/Saturation.lean
> +  sorry
Yes, unfortunately this is essential for one direction of the bijection. `sheaves_respect_iff_covering` is a key lemma for `Duality.lean`.

2024-11-20 13:29 UTC, doctorn commented on ToposTheory/Saturation.lean
> +  sorry
It might be possible to give a better proof of `sheaves_respect_iff_covering` that doesn't use this or a related fact but I couldn't find one in time.

2024-11-20 13:29 UTC, doctorn commented on ToposTheory/Duality.lean
> +import ToposTheory.GrothendieckSubtopos
Sorry about this--I will do

2024-11-20 13:30 UTC, doctorn commented on ToposTheory/Duality.lean
> +variable {C : Type u} [SmallCategory C]
Ah ok--I was mostly taking style hints from the MathLib files I was reading, but hadn't read the guidlines carefully. I'll go back over with this in mind.

2024-11-20 13:32 UTC, doctorn commented on ToposTheory/Duality.lean
> +      (S.pullback (g ≫ f)).functor ≅ ((S.pullback f).pullback g).functor where
I can't remember. It seemed important at the time, but looking now I'm less sure. When I'm back looking at this I'll see if I can do without.

2024-11-20 13:33 UTC, doctorn commented on ToposTheory/Duality.lean
> +  def pullback_comp_functor_eq {X : C} (S : Sieve X) {Y Z : C} (f : Y ⟶ X) (g : Z ⟶ Y) :
This is `CategoryTheory.Sieve.pullback_comp` extended to applications of `Sieve.functor`. Again, I can't quite remember now why I thought I needed this but I can see if I can do without.

2024-12-10 14:33 UTC, closed without merging